Ships6/Models/Destination.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace Ships6.Models
{
    public class Destination
    {
        [Key]
        public int DestinationID { get; set; }

        [Display(Name = "Destination Name")]
        public string DestinationName { get; set; }

        [Display(Name = "Country")]
        public string DestinationCountry { get; set; }

        [Display(Name = "Image")]
        public byte[] DestinationImage { get; set; }
    }


    /*public class DestinationCreateViewModel
    {
        public int DestinationName { get; set; }
        public string DestinationCountry { get; set; }
        public HttpPostedFile DestinationImage { get; set; }
    }*/
}

Ships6/Controllers/DestinationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ships6.Models;

namespace Ships6.Controllers
{
    public class DestinationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Destinations
        public ActionResult Index()
        {
            return View(db.Destinations.ToList());
        }

        // GET: Destinations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // GET: Destinations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Destinations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DestinationID,DestinationName,DestinationCountry,DestinationImage")] Destination destination, HttpPostedFileBase imageFile = null)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    destination.DestinationImage = new byte[imageFile.ContentLength];
                    imageFile.InputStream.Read(destination.DestinationImage, 0, imageFile.ContentLength);
                }

                db.Destinations.Add(destination);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(destination);
        }

        // GET: Destinations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DestinationID,DestinationName,DestinationCountry")] Destination destination, HttpPostedFileBase imageFile = null)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    destination.DestinationImage = new byte[imageFile.ContentLength];
                    imageFile.InputStream.Read(destination.DestinationImage, 0, imageFile.ContentLength);
                }

                db.Entry(destination).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(destination);
        }

        // GET: Destinations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Destination destination = db.Destinations.Find(id);
            db.Destinations.Remove(destination);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ships6/Views/Destinations/Delete.cshtml
@model Ships6.Models.Destination

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Destination</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DestinationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Ships6/Views/Destinations/Details.cshtml
@model Ships6.Models.Destination

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Destination</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DestinationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DestinationImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DestinationImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DestinationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Ships6/Views/Destinations/Edit.cshtml
@model Ships6.Models.Destination

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Destinations", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Destination</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DestinationID)

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DestinationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinationCountry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinationCountry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DestinationCountry, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class="control-label col-md-2" for="imageFile">Image</label>
            <div class="col-md-10">
                <input type="file" name="imageFile" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ships6/Views/Destinations/Index.cshtml
@model IEnumerable<Ships6.Models.Destination>

@{
    ViewBag.Title = "Destinations Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DestinationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationCountry)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinationImage)            
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.DestinationName
        </td>
        <td>
            @item.DestinationCountry 
        </td>
        <td>
            @if (item.DestinationImage != null){
                <img src="data:image;base64,@System.Convert.ToBase64String(item.DestinationImage)" width="80" height="80" />
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DestinationID }) |
            @Html.ActionLink("Details", "Details", new { id=item.DestinationID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DestinationID })
        </td>
    </tr>
}

</table>