Ships6/Controllers/CruisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ships6.Models;
using System.Diagnostics;

namespace Ships6.Controllers
{
    public class CruisesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cruises
        [Authorize(Roles = "canEdit")]
        public ActionResult Index()
        {
            var cruises = db.Cruises.Include(c => c.Operator);
            return View(cruises.ToList());
        }

        // GET: Cruises/Details/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cruise cruise = db.Cruises.Find(id);
            if (cruise == null)
            {
                return HttpNotFound();
            }
            return View(cruise);
        }

        // GET: Cruises/Create
        [Authorize(Roles = "canEdit")]
        public ActionResult Create()
        {
            ViewBag.OperatorID = new SelectList(db.Operators, "OperatorID", "OperatorName");
            ViewBag.DestinationsList = new SelectList(db.Destinations,"DestinationID","DestinationName");
            ViewBag.DestinationNum = 6;
            return View();
        }

        // POST: Cruises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Create([Bind(Include = "CruiseID,OperatorID,CruiseName,CruiseDescription,CruiseImage,CruisePrice,CruiseDepartureTime,CruiseDayLength")] Cruise cruise,
                                    FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                //Debug.WriteLine("dEBUG: WE GOT THIS: " + collection["destination1"].ToString());
                db.Cruises.Add(cruise);
                db.SaveChanges();

                db.Entry(cruise).GetDatabaseValues();
                int cruiseID = cruise.CruiseID;

                var destinations = collection.AllKeys
                                    .Where(k => k.StartsWith("destinationChoice"))
                                    .ToDictionary(k => k, k => collection[k]);
                int counter = 1;
                foreach (KeyValuePair<string,string> pair in destinations){
                    Debug.WriteLine("Key is: " + pair.Key + " While Value is " + pair.Value);
                    db.CruiseDestinations.Add(
                        new CruiseDestination
                        {
                            CruiseID = cruiseID,
                            DestinationID = int.Parse(pair.Value),
                            tripOrder = counter
                        }                    
                    );
                    counter++;
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.OperatorID = new SelectList(db.Operators, "OperatorID", "OperatorName", cruise.OperatorID);
            return View(cruise);
        }

        // GET: Cruises/Edit/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit(int? id)
        {
            ViewBag.DestinationsList = new SelectList(db.Destinations, "DestinationID", "DestinationName");
            ViewBag.DestinationNum = 6;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cruise cruise = db.Cruises.Find(id);
            if (cruise == null)
            {
                return HttpNotFound();
            }
            ViewBag.OperatorID = new SelectList(db.Operators, "OperatorID", "OperatorName", cruise.OperatorID);


            return View(cruise);
        }

        // POST: Cruises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult Edit([Bind(Include = "CruiseID,OperatorID,CruiseName,CruiseDescription,CruiseImage,CruisePrice,CruiseDepartureTime,CruiseDayLength")] Cruise cruise, 
            FormCollection collection, HttpPostedFileBase imageFile = null)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    cruise.CruiseImage = new byte[imageFile.ContentLength];
                    imageFile.InputStream.Read(cruise.CruiseImage, 0, imageFile.ContentLength);
                }

                db.Entry(cruise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            int cruiseID = cruise.CruiseID;
            var destinations = collection.AllKeys
                                .Where(k => k.StartsWith("destinationChoice"))
                                .ToDictionary(k => k, k => collection[k]);
            int counter = 1;
            foreach (KeyValuePair<string, string> pair in destinations)
            {
                Debug.WriteLine("Key is: " + pair.Key + " While Value is " + pair.Value);
                db.CruiseDestinations.Add(
                    new CruiseDestination
                    {
                        CruiseID = cruiseID,
                        DestinationID = int.Parse(pair.Value),
                        tripOrder = counter
                    }
                );
                counter++;
            }
            db.SaveChanges();


            ViewBag.OperatorID = new SelectList(db.Operators, "OperatorID", "OperatorName", cruise.OperatorID);
            return View(cruise);
        }

        // GET: Cruises/Delete/5
        [Authorize(Roles = "canEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cruise cruise = db.Cruises.Find(id);
            if (cruise == null)
            {
                return HttpNotFound();
            }
            return View(cruise);
        }

        // POST: Cruises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]
        public ActionResult DeleteConfirmed(int id)
        {
            Cruise cruise = db.Cruises.Find(id);
            db.Cruises.Remove(cruise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "canEdit")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ships6/Views/Cruises/Edit.cshtml
@model Ships6.Models.Cruise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@{/*Html.BeginForm("Create", "Cruises", FormMethod.Post, new { enctype = "multipart/form-data" })*/}
@using (Html.BeginForm("Edit", "Cruises", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Cruise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CruiseID)

        <div class="form-group">
            @Html.LabelFor(model => model.OperatorID, "OperatorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OperatorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OperatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CruiseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CruiseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CruiseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CruiseDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CruiseDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CruiseDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CruisePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CruisePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CruisePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CruiseDepartureTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CruiseDepartureTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CruiseDepartureTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CruiseDayLength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CruiseDayLength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CruiseDayLength, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--
        <div class="form-group">
            <label>Destinations</label>
        </div>
        @for (int i = 1; i <= (int)ViewBag.DestinationNum; i++)
        {
            <div class="form-group">
                <div class="input-field">
                    @Html.DropDownList("destinationChoice" + i.ToString(), (SelectList)ViewBag.DestinationsList, new { @class = "browser-default" })
                </div>
            </div>
        }-->


        <div class="form-group">
            <label class="control-label col-md-2" for="imageFile">Image</label>
            <div class="col-md-10">
                <input type="file" name="imageFile" class="form-control" />
            </div>
        </div>



        <br/><br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ships6/Views/Cruises/Index.cshtml
@model IEnumerable<Ships6.Models.Cruise>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Operator.OperatorName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CruiseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CruiseDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CruiseImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CruisePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CruiseDepartureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CruiseDayLength)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Operator.OperatorName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CruiseName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CruiseDescription)
        </td>
        <td>
            @if (item.CruiseImage != null)
            {
                <img src="data:image;base64,@System.Convert.ToBase64String(item.CruiseImage)" width="80" height="80" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CruisePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CruiseDepartureTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CruiseDayLength)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CruiseID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CruiseID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CruiseID })
        </td>
    </tr>
}

</table>